### ISSUE TITLE
Help needed - Installer fails

### ISSUE THREAD

**Issue by tjsd** [endeavouros-team/EndeavourOS-Development#1]
Unsure where to go for help, and this might not be the place at all. But my installer fails, I have tried several times. 
I tried default choices with KDE, then several times with different mirrors selected.

It says pacman failed and here is the log:
https://termbin.com/2hf9

**Comment by tjsd** [comment]
We discussed it in the forums and there seems to be a path error in the installer
ref: https://forum.endeavouros.com/t/calamares-fails-maybe-pacman-issue/22638

**Comment by killajoe** [comment]
fixed by this workaround till the next release:
https://github.com/endeavouros-team/EndeavourOS-calamares/commit/af37b2eb1c5e52ad234009b64c98c07e4006aee9
