### ISSUE TITLE
Translation error - dutch

### ISSUE THREAD

**Issue by rthijs** [endeavouros-team/EndeavourOS-Development#2]
Hi,

I'm not sure if this is the right place but there is a translation error that shows up every time a package is installed
![bug_bronned](https://user-images.githubusercontent.com/16205691/153745513-3f7a4741-4506-4eac-8f92-811c7f86e92f.png)
.

The line for, what I assume is, "Sources are ready." in english sais "Bronned zijn gereed.". This should be "Bronnen zijn gereed.".

**Comment by killajoe** [comment]
this GitHub repository is only for the info webpage ;) so sorry if no one get into your issue.. 
If this is yay you are talking about? we do not develop the source for it and translations will be maintained at the source here:
https://www.transifex.com/yay/yay-aur-helper/
