### ISSUE TITLE
 Job for tor.service failed because the control process exited with error code. See "systemctl status tor.service" and "journalctl -xeu tor.service" for details.

### ISSUE THREAD

**Issue by CyberGhazi786** [endeavouros-team/EndeavourOS-Development#5]
Hi,

I wanna install tor proxy chains anonsurf on Endeavour OS and 
I tried all the ways but got this errors.

Method Used Here Is : https://gist.github.com/valyakuttan/ce4afb62288120cd5ecef0fde4ea63c4#file-install-tor-on-arch-linux-md

But got these errors :-(

Job for tor.service failed because the control process exited with error code.
See "systemctl status tor.service" and "journalctl -xeu tor.service" for details.

Please help, I dont know what to do now ? teach us a easy solution with click click or few commands or using bash script to save time energy and efforts.

cyberghazi786
Self Taught Pentester :-)

Method Used Here Is : https://gist.github.com/valyakuttan/ce4afb62288120cd5ecef0fde4ea63c4#file-install-tor-on-arch-linux-md

**Comment by killajoe** [comment]
this is only information about the Development not to create Bug reports or ask questions about the Distribution. 
We have a chat on telegram: https://t.me/Endeavouros
Or join the forum here: https://forum.endeavouros.com
