### ISSUE TITLE
How to import BLACKARCH CyberSecurity tools using "pacman -S command" in Endeavour Linux ? 

### ISSUE THREAD

**Issue by CyberGhazi786** [endeavouros-team/EndeavourOS-Development#6]
Hi,

I just installed your distro on my Vmware and I got shocked to see it works like a charm.
But I dont know to install different CyberSecurity Auditing Tools from BLACKARCH tools repository using magic command :-)
pacman -S toolname ? 

Please help and give us a easily click click or automated installation solution. 

Thanks
cyberghazi786
Self Taught Pentester :-)

**Comment by killajoe** [comment]
this is only information about the Development not to create Bug reports or ask questions about the Distribution. 
We have a chat on telegram: https://t.me/Endeavouros
Or join the forum here: https://forum.endeavouros.com
