### ISSUE TITLE
Endeavour OS live USB isn't booting 

### ISSUE THREAD

**Issue by sebi-vscode2** [endeavouros-team/EndeavourOS-Development#7]
Hello, I wanted to try the distro but I had this error on boot: 

![20221222_104046.jpg](https://user-images.githubusercontent.com/93952788/209146665-875b6dd7-b65f-446d-80c6-e8714309a60a.jpg)

can someone help me solve it?

**Comment by killajoe** [comment]
> can someone help me solve it?

not at the i see issue  tracker for the infopage..
