### ISSUE TITLE
Suspend is broken in Asus laptops on latest kernel

### ISSUE THREAD

**Issue by hfc2x** [endeavouros-team/EndeavourOS-Development#9]
Hello there, dev team, and happy new year!

I've been having this issue where my laptop freezes when attempting to suspend when running the latest kernel. These problems only started when I updated to the latest kernel the other day. There's a lot more detail in my forum post [here](https://forum.endeavouros.com/t/laptop-crashes-immediately-when-suspending/35419). My laptop is an Asus ROG GL-553VE model.

Forum user petsam suggested running the LTS kernel, and I have not run into this issue at all in the days since, when there was a very high probability my laptop would freeze immediately upon attempting suspend on the latest kernel.

**Comment by killajoe** [comment]
totally the wrong place.. to ask for support..  this would be to place issues with the info page..
